from setuptools import setup, find_packages

setup(
    name="architector-llm-backend",
    version="2.1.0",
    description="Backend engine and architecture documentation generator for Architector-LLM",
    author="Engr. Hammad Khurshid",
    author_email="engr.hammadkhurshid@gmail.com",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.9",
    install_requires=[
        "flask>=3.0.0",
        "flask-cors>=4.0.0",
        "gunicorn>=21.2.0",
        "python-dotenv>=1.0.0",
        "requests>=2.31.0",
        "tree-sitter==0.23.2",
        "tree-sitter-python==0.23.2",
        "tree-sitter-javascript==0.23.1",
        "tree-sitter-typescript==0.23.2",
        "tree-sitter-php==0.23.2",
        "tree-sitter-java==0.23.2",
        "tree-sitter-c==0.23.2",
        "tree-sitter-cpp==0.23.2",
        "tree-sitter-c-sharp==0.23.1",
        "tree-sitter-go==0.23.2",
        "tree-sitter-rust==0.23.2",
        "tree-sitter-ruby==0.23.1",
    ],
)
