"""
Interactive Documentation Generator
Creates enhanced documentation with cross-references, navigation, and comparisons.
"""

from typing import Dict, List, Any
import os


class InteractiveDocGenerator:
    """Generates interactive documentation with cross-links and navigation."""
    
    def generate_enhanced_index(
        self,
        diagram_results: Dict[str, Any],
        validation_results: Dict[str, Any],
        relationship_map: Dict[str, Any],
        metadata: Dict[str, Any]
    ) -> str:
        """
        Generate comprehensive interactive index with cross-references.
        
        Args:
            diagram_results: Generated diagrams
            validation_results: Quality validation results
            relationship_map: Cross-diagram relationships
            metadata: Generation metadata
            
        Returns:
            Enhanced INDEX.md content
        """
        index = f"""# 📚 Architecture Documentation Index

**Generated:** {metadata.get('generated_at', 'N/A')}  
**Version:** {metadata.get('semantic_version', '1.0.0')}  
**Project:** {os.path.basename(metadata.get('codebase_path', 'Unknown'))}

---

## 🎯 Quick Navigation

{self._generate_quick_nav(diagram_results, validation_results)}

---

## 📊 Diagrams by Category

{self._generate_category_sections(diagram_results, validation_results, relationship_map)}

---

## 🔗 Cross-References

{self._generate_cross_references(relationship_map)}

---

## 📈 Quality Metrics

{self._generate_quality_summary(validation_results)}

---

## 🗺️ Documentation Map

```
📁 Architecture Documentation
├── 📄 README.md (Main documentation)
├── 📊 QUALITY_REPORT.md (Quality assessment)
├── 🔗 RELATIONSHIPS.md (Cross-diagram analysis)
├── 📁 diagrams/
{self._generate_file_tree(diagram_results)}
├── 📁 docs/
│   ├── structural-diagrams.md
│   ├── behavioral-diagrams.md
│   └── data-diagrams.md
└── 📁 metadata/
    └── generation_info.json
```

---

## 🚀 Getting Started

1. **Overview:** Start with [README.md](README.md) for project overview
2. **Architecture:** Review structural diagrams in [docs/structural-diagrams.md](docs/structural-diagrams.md)
3. **Behavior:** Understand workflows in [docs/behavioral-diagrams.md](docs/behavioral-diagrams.md)
4. **Quality:** Check [QUALITY_REPORT.md](QUALITY_REPORT.md) for diagram quality
5. **Relationships:** Explore [RELATIONSHIPS.md](RELATIONSHIPS.md) for cross-references

---

*Generated by Architector-LLM Interactive Documentation System*
"""
        return index
    
    def _generate_quick_nav(self, diagram_results: Dict, validation_results: Dict) -> str:
        """Generate quick navigation links."""
        nav = "| Diagram | Type | Quality | Quick Link |\n"
        nav += "|---------|------|---------|------------|\n"
        
        for diagram_type, result in diagram_results.items():
            if result.get('success'):
                name = result.get('metadata', {}).get('name', diagram_type.replace('_', ' ').title())
                category = result.get('metadata', {}).get('category', 'Other')
                
                # Quality badge
                if validation_results and diagram_type in validation_results:
                    score = validation_results[diagram_type].get('overall_score', 0)
                    emoji = "🟢" if score >= 85 else "🟡" if score >= 70 else "🔴"
                    quality = f"{score:.0f}/100 {emoji}"
                else:
                    quality = "N/A"
                
                nav += f"| [{name}](diagrams/{diagram_type}.mmd) | {category} | {quality} | [PNG](diagrams/{diagram_type}.png) · [SVG](diagrams/{diagram_type}.svg) |\n"
        
        return nav
    
    def _generate_category_sections(
        self,
        diagram_results: Dict,
        validation_results: Dict,
        relationship_map: Dict
    ) -> str:
        """Generate sections grouped by diagram category."""
        categories = {}
        
        for diagram_type, result in diagram_results.items():
            if result.get('success'):
                category = result.get('metadata', {}).get('category', 'Other')
                if category not in categories:
                    categories[category] = []
                categories[category].append((diagram_type, result))
        
        sections = ""
        for category in sorted(categories.keys()):
            sections += f"### {category} Diagrams\n\n"
            
            for diagram_type, result in categories[category]:
                name = result.get('metadata', {}).get('name', diagram_type.replace('_', ' ').title())
                sections += f"#### [{name}](diagrams/{diagram_type}.png)\n\n"
                
                # Quality score
                if validation_results and diagram_type in validation_results:
                    val = validation_results[diagram_type]
                    score = val.get('overall_score', 0)
                    emoji = "🟢" if score >= 85 else "🟡" if score >= 70 else "🔴"
                    sections += f"**Quality:** {score:.0f}/100 {emoji}  \n"
                
                # Purpose
                purpose = result.get('metadata', {}).get('purpose', 'N/A')
                sections += f"**Purpose:** {purpose}  \n"
                
                # Related diagrams
                related = self._find_related_diagrams(diagram_type, relationship_map)
                if related:
                    related_links = ", ".join([f"[{r.replace('_', ' ').title()}](diagrams/{r}.png)" for r in related[:3]])
                    sections += f"**Related:** {related_links}  \n"
                
                sections += f"\n📄 [Source](diagrams/{diagram_type}.mmd) | 🖼️ [PNG](diagrams/{diagram_type}.png) | 🎨 [SVG](diagrams/{diagram_type}.svg)\n\n"
                sections += "---\n\n"
        
        return sections
    
    def _find_related_diagrams(self, diagram_type: str, relationship_map: Dict) -> List[str]:
        """Find diagrams related to the given diagram."""
        related = []
        
        connections = relationship_map.get('diagram_connections', [])
        for conn in connections:
            if conn['from'] == diagram_type:
                related.append(conn['to'])
            elif conn['to'] == diagram_type:
                related.append(conn['from'])
        
        return related
    
    def _generate_cross_references(self, relationship_map: Dict) -> str:
        """Generate cross-reference section."""
        shared = relationship_map.get('shared_entities', {})
        
        if not shared:
            return "*No shared entities found across diagrams.*"
        
        refs = "### Entities Across Multiple Diagrams\n\n"
        
        # Show top entities
        sorted_entities = sorted(shared.items(), key=lambda x: len(x[1]), reverse=True)
        
        for entity, diagrams in sorted_entities[:10]:
            diagram_links = ", ".join([f"[{d.replace('_', ' ').title()}](diagrams/{d}.png)" for d in diagrams])
            refs += f"- **{entity}**: {diagram_links}\n"
        
        return refs
    
    def _generate_quality_summary(self, validation_results: Dict) -> str:
        """Generate quality metrics summary."""
        if not validation_results:
            return "*Quality validation not available.*"
        
        scores = [v.get('overall_score', 0) for v in validation_results.values()]
        avg_score = sum(scores) / len(scores) if scores else 0
        
        summary = f"**Average Quality Score:** {avg_score:.1f}/100\n\n"
        summary += "| Metric | Score |\n"
        summary += "|--------|-------|\n"
        
        # Calculate dimension averages
        dimensions = ['syntax', 'completeness', 'clarity', 'accuracy']
        for dim in dimensions:
            dim_scores = [v.get('scores', {}).get(dim, 0) for v in validation_results.values()]
            avg = sum(dim_scores) / len(dim_scores) if dim_scores else 0
            emoji = "✅" if avg >= 85 else "⚠️" if avg >= 70 else "❌"
            summary += f"| {dim.title()} | {avg:.1f}/100 {emoji} |\n"
        
        summary += f"\n📊 [View Full Quality Report](QUALITY_REPORT.md)"
        
        return summary
    
    def _generate_file_tree(self, diagram_results: Dict) -> str:
        """Generate file tree for diagrams folder."""
        tree = ""
        for diagram_type in sorted(diagram_results.keys()):
            if diagram_results[diagram_type].get('success'):
                tree += f"│   ├── {diagram_type}.mmd\n"
                tree += f"│   ├── {diagram_type}.png\n"
                tree += f"│   └── {diagram_type}.svg\n"
        return tree
    
    def generate_comparison_view(
        self,
        diagram_results: Dict[str, Any],
        relationship_map: Dict[str, Any]
    ) -> str:
        """Generate side-by-side comparison documentation."""
        doc = """# 🔄 Diagram Comparison View

This document provides side-by-side comparisons of related diagrams.

---

"""
        
        connections = relationship_map.get('diagram_connections', [])
        
        for i, conn in enumerate(connections[:5], 1):  # Top 5 connections
            from_type = conn['from']
            to_type = conn['to']
            shared = conn.get('shared_entities', [])
            
            from_name = from_type.replace('_', ' ').title()
            to_name = to_type.replace('_', ' ').title()
            
            doc += f"## Comparison {i}: {from_name} vs {to_name}\n\n"
            doc += f"**Connection Strength:** {conn['connection_strength']} shared entities  \n"
            doc += f"**Relationship Type:** {conn['relationship_type'].replace('_', ' ').title()}  \n"
            doc += f"**Shared Entities:** {', '.join(shared[:5])}\n\n"
            
            doc += "### Side-by-Side View\n\n"
            doc += f"| {from_name} | {to_name} |\n"
            doc += "|-------------|-------------|\n"
            doc += f"| ![{from_name}](diagrams/{from_type}.png) | ![{to_name}](diagrams/{to_type}.png) |\n"
            doc += f"| [View Details](diagrams/{from_type}.mmd) | [View Details](diagrams/{to_type}.mmd) |\n\n"
            
            doc += "### Key Insights\n\n"
            doc += f"- Both diagrams share {len(shared)} entities\n"
            doc += f"- Provides complementary views of: {', '.join(shared[:3])}\n"
            doc += f"- Use together for complete understanding\n\n"
            doc += "---\n\n"
        
        return doc
    
    def generate_navigation_sidebar(
        self,
        diagram_results: Dict[str, Any],
        validation_results: Dict[str, Any]
    ) -> str:
        """Generate navigation content for sidebar (useful for web docs)."""
        nav = "# Navigation\n\n"
        
        # By category
        categories = {}
        for diagram_type, result in diagram_results.items():
            if result.get('success'):
                category = result.get('metadata', {}).get('category', 'Other')
                if category not in categories:
                    categories[category] = []
                categories[category].append(diagram_type)
        
        for category in sorted(categories.keys()):
            nav += f"## {category}\n\n"
            for diagram_type in sorted(categories[category]):
                name = diagram_type.replace('_', ' ').title()
                
                # Quality indicator
                if validation_results and diagram_type in validation_results:
                    score = validation_results[diagram_type].get('overall_score', 0)
                    emoji = "🟢" if score >= 85 else "🟡" if score >= 70 else "🔴"
                    nav += f"- {emoji} [{name}](diagrams/{diagram_type}.png)\n"
                else:
                    nav += f"- [{name}](diagrams/{diagram_type}.png)\n"
            nav += "\n"
        
        return nav
